b1u1 = {
    'l1': [
        ['はじめまして', ['nice to meet you', 'how do you do']],
        ['わたし', ['I', 'me']],
        ['ぼく', 'I (used by males)'],
        ['です', ['am', 'is', 'are']],
        ['どぞうよろしく', ['nice to meet you', 'it\'s a pleasure']],
    ],
    'l2': [
        ['おはよう', 'good morning (informal)'],
        ['おはようございます', 'good morning (formal)'],
        ['こんにちは', ['hello', 'hi']],
        ['さようなら', 'goodbye'],
        ['やまだせんせい', 'teacher Yamada'],
        ['まりさん', ['Mary', 'Mari']],
        ['はい', 'yes'],
    ],
    'l3': [
        ['はじめましょう', 'let\'s begin'],
        ['きりつ', 'stand (formal)'],
        ['れい', 'bow (formal)'],
        ['ちゃくせき', 'sit (formal)'],
        ['～は（お）やすみです', '(~) is absent'],
        ['～はちこくです', '(~) is late'],
        ['はやく', 'hurry'],
        ['おわりましょう', 'let\'s finish'],
        ['これ', 'this'],
        [['なに', 'なん'], 'what'],
        ['か', ['?', 'question']],
    ],
    'l4': [
        ['すみません。もういちどおねがいします', 'excuse me. (repeat) it one more time.'],
        ['ゆっくりおねがいします', 'slowly please.'],
        ['ちょっとまってください', 'please wait a minute.'],
        ['（どうも）ありがとう（ございます）', 'thank you (very much)'],
        ['どういたしまして', 'you\'re welcome'],
    ],
    'l5': [
        ['それ', 'that one (near listener)'],
        ['あれ' 'that one (over there)'],
        ['いいえ', 'no'],
        ['はい、そうです', 'yes, it is'],
        ['いいえ、そうではありません', 'no, it isn\'t'],
    ],
    'l6': [
        ['あついですねえ', 'it\'s hot'],
        ['さむいですねえ', 'it\'s cols'],
        ['すずしいですねえ', 'it\'s cool'],
        ['そうですねえ', 'yes it is'],
        ['（お）げんきですか', 'how are you'],
        ['はい、げんきです', 'I am fine'],
        ['むしあついですねえ', 'it\'s hot and humid'],
        ['いい（お）てんきですねえ', 'the weather is nice'],
        ['あめですねえ', 'it\'s raining'],
    ],
    'all': [
        ['はじめまして', ['nice to meet you', 'how do you do']],
        ['わたし', ['I', 'me']],
        ['ぼく', 'I (used by males)'],
        ['です', ['am', 'is', 'are']],
        ['どぞうよろしく', ['nice to meet you', 'it\'s a pleasure']],
        ['おはよう', 'good morning (informal)'],
        ['おはようございます', 'good morning (formal)'],
        ['こんにちは', ['hello', 'hi']],
        ['さようなら', 'goodbye'],
        ['やまだせんせい', 'teacher Yamada'],
        ['まりさん', ['Mary', 'Mari']],
        ['はい', 'yes'],
        ['はじめましょう', 'let\'s begin'],
        ['きりつ', 'stand (formal)'],
        ['れい', 'bow (formal)'],
        ['ちゃくせき', 'sit (formal)'],
        ['～は（お）やすみです', '(~) is absent'],
        ['～はちこくです', '(~) is late'],
        ['はやく', 'hurry'],
        ['おわりましょう', 'let\'s finish'],
        ['これ', 'this'],
        [['なに', 'なん'], 'what'],
        ['か', ['?', 'question']],
        ['すみません。もういちどおねがいします', 'excuse me. (repeat) it one more time.'],
        ['ゆっくりおねがいします', 'slowly please.'],
        ['ちょっとまってください', 'please wait a minute.'],
        ['（どうも）ありがとう（ございます）', 'thank you (very much)'],
        ['どういたしまして', 'you\'re welcome'],
        ['それ', 'that one (near listener)'],
        ['あれ' 'that one (over there)'],
        ['いいえ', 'no'],
        ['はい、そうです', 'yes, it is'],
        ['いいえ、そうではありません', 'no, it isn\'t'],
        ['あついですねえ', 'it\'s hot'],
        ['さむいですねえ', 'it\'s cols'],
        ['すずしいですねえ', 'it\'s cool'],
        ['そうですねえ', 'yes it is'],
        ['（お）げんきですか', 'how are you'],
        ['はい、げんきです', 'I am fine'],
        ['むしあついですねえ', 'it\'s hot and humid'],
        ['いい（お）てんきですねえ', 'the weather is nice'],
        ['あめですねえ', 'it\'s raining'],
    ]
}

# a
b1u2 = {}

b1u3 = {}

b1u4 = {}

b1u5 = {}

b1u6 = {}

b1u7 = {}

b1u8 = {
    'l1': [
        ['います', ['there is (animate obj.)', 'are (animate obj.)']],
        ['あります', ['there is (inanimate obj.)', 'are (inanimate obj.)']],
        ['そと', 'outside'],
        ['ドア', 'door'],
        ['まど', 'window'],
        ['つくえ', 'desk'],
        ['いす', 'chair'],
        ['えんぴつけすり', 'pencil case'],
        ['ごみばこ', 'garbage can'],
        ['いぬ', 'dog'],
        ['ねこ', 'cat'],
        ['また', 'again'],
    ],
    'l2': [
        ['おとこ', 'male'],
        ['おんな', 'female'],
        ['ひと', 'person'],
        ['こども', 'child'],
        ['おとこのひと', 'male'],
        ['おんなのひと', 'female'],
        ['おとこのこ', 'boy'],
        ['おんなのこ', 'girl'],
        [['トイレ', '（を）てあらい'], ['toilet', 'bathroom', 'restroom']],
        ['プール', 'pool'],
        [['このかた', 'あのかた'], 'person (polite)'],
    ],
    'l3': [
        ['き', 'tree'],
        ['はな', 'flower'],
        ['いけ', 'pond'],
        ['さかな', 'fish'],
        ['とり', 'bird'],
        ['たくさん', ['a lot', 'many']],
        ['すこし', ['a few', 'little']],
    ],
    'l4': [
        ['たてもの', 'building'],
        ['じむしょ' 'office'],
        ['きょうしつ', 'classroom'],
        ['ロッカー', 'locker'],
        ['あたらし', 'new'],
        ['ふるい', 'old'],
        ['うつくしい', 'beautiful'],
        ['ゆうめい', 'famous'],
    ],
    'all': [
        ['います', ['there is (animate obj.)', 'are (animate obj.)']],
        ['あります', ['there is (inanimate obj.)', 'are (inanimate obj.)']],
        ['そと', 'outside'],
        ['ドア', 'door'],
        ['まど', 'window'],
        ['つくえ', 'desk'],
        ['いす', 'chair'],
        ['えんぴつけすり', 'pencil case'],
        ['ごみばこ', 'garbage can'],
        ['いぬ', 'dog'],
        ['ねこ', 'cat'],
        ['また', 'again'],
        ['おとこ', 'male'],
        ['おんな', 'female'],
        ['ひと', 'person'],
        ['こども', 'child'],
        ['おとこのひと', 'male'],
        ['おんなのひと', 'female'],
        ['おとこのこ', 'boy'],
        ['おんなのこ', 'girl'],
        [['トイレ', '（を）てあらい'], ['toilet', 'bathroom', 'restroom']],
        ['プール', 'pool'],
        [['このかた', 'あのかた'], 'person (polite)'],
        ['き', 'tree'],
        ['はな', 'flower'],
        ['いけ', 'pond'],
        ['さかな', 'fish'],
        ['とり', 'bird'],
        ['たくさん', ['a lot', 'many']],
        ['すこし', ['a few', 'little']],
        ['たてもの', 'building'],
        ['じむしょ' 'office'],
        ['きょうしつ', 'classroom'],
        ['ロッカー', 'locker'],
        ['あたらし', 'new'],
        ['ふるい', 'old'],
        ['うつくしい', 'beautiful'],
        ['ゆうめい', 'famous'],
    ],
    'kanji': [
        ['人', 'ひと'],
        ['子', 'こ'],
        ['女', 'おんな'],
        ['好（き）', 'すき'],
        ['田', ['た', 'だ']],
        ['男', 'おとこ'],
        ['私', 'わたし'],
    ]
}

b1u9 = {
    'l1': [
        ['しゃかい', 'social studies'],
        ['かがく', 'science'],
        ['すうがく', 'math'],
        ['えいご', 'english'],
        ['がいこくご', 'foreign language'],
        ['びじゅつ', 'art'],
        ['たいいく', ['physical education', 'gym']],
        ['ホームルーム', 'homeroom'],
        ['やすみじかん', 'a break'],
        ['かもく', 'subject(s)'],
        [['じゅぎょう', 'クラス'], 'class/instruction'],
        ['あります', 'to have'],
    ],
    'l2': [
        ['つぎ', 'next'],
        ['むずかしい', 'difficult'],
        ['やさしい', 'easy'],
        ['たのしい', 'fun/enjoyable'],
        ['おもしろい', 'interesting'],
        ['つまらない', 'boring/uninteresting'],
    ],
    'l3': [
        [['なぜ', 'どうして'], 'why'],
        ['せいせき', 'grade'],
        ['ひどい', 'terrible'],
        ['うれしい', 'glad/happy'],
        ['かなしい', 'sad'],
        ['おととい', 'the day before yesterday'],
        ['あさって', 'the day after tomorrow'],
        ['いいですねえ', 'how nice (present)'],
        ['よかったですねえ', 'how nice (past)'],
        ['ざっねんでしめえ', 'how disappointing, (present)'],
        ['ざんでんでしたねえ', 'how disappointing (past)'],
    ],
    'l4': [
        ['せんしゅう', 'last week'],
        ['こんしゅう', 'this week'],
        ['らいしゅう', 'next week'],
        ['まいしゅう', 'every week'],
        ['しゅうまつ', 'weekend'],
        ['おおい', ['are many', 'much']],
        ['すくない', ['are few', 'little']],
        ['～がほしい', 'want (something)'],
        ['たいへん', 'hard/difficult'],
        ['それに', 'moreover/besides'],
    ],
    'l5': [
        ['ほうかご', 'after school'],
        ['きょねん', 'last year'],
        ['ことし', 'this year'],
        ['らいねん', 'next year'],
        [['まいとし', 'まいねん'], 'every year'],
        ['バンド', 'band'],
        ['れんしゅう', 'practice'],
        ['うたいます', 'to sing'],
        ['およぎます', 'to swim'],
        ['あそうびます', ['to play', 'amuse']],
        ['ゲームをします', 'to play a game'],
    ],
    'all': [
        ['しゃかい', 'social studies'],
        ['かがく', 'science'],
        ['すうがく', 'math'],
        ['えいご', 'english'],
        ['がいこくご', 'foreign language'],
        ['びじゅつ', 'art'],
        ['たいいく', ['physical education', 'gym']],
        ['ホームルーム', 'homeroom'],
        ['やすみじかん', 'a break'],
        ['かもく', 'subject(s)'],
        [['じゅぎょう', 'クラス'], 'class/instruction'],
        ['あります', 'to have'],
        ['つぎ', 'next'],
        ['むずかしい', 'difficult'],
        ['やさしい', 'easy'],
        ['たのしい', 'fun/enjoyable'],
        ['おもしろい', 'interesting'],
        ['つまらない', 'boring/uninteresting'],
        [['なぜ', 'どうして'], 'why'],
        ['せいせき', 'grade'],
        ['ひどい', 'terrible'],
        ['うれしい', 'glad/happy'],
        ['かなしい', 'sad'],
        ['おととい', 'the day before yesterday'],
        ['あさって', 'the day after tomorrow'],
        ['いいですねえ', 'how nice (present)'],
        ['よかったですねえ', 'how nice (past)'],
        ['ざっねんでしめえ', 'how disappointing, (present)'],
        ['ざんでんでしたねえ', 'how disappointing (past)'],
        ['せんしゅう', 'last week'],
        ['こんしゅう', 'this week'],
        ['らいしゅう', 'next week'],
        ['まいしゅう', 'every week'],
        ['しゅうまつ', 'weekend'],
        ['おおい', ['are many', 'much']],
        ['すくない', ['are few', 'little']],
        ['～がほしい', 'want (something)'],
        ['たいへん', 'hard/difficult'],
        ['それに', 'moreover/besides'],
        ['ほうかご', 'after school'],
        ['きょねん', 'last year'],
        ['ことし', 'this year'],
        ['らいねん', 'next year'],
        [['まいとし', 'まいねん'], 'every year'],
        ['バンド', 'band'],
        ['れんしゅう', 'practice'],
        ['うたいます', 'to sing'],
        ['およぎます', 'to swim'],
        ['あそうびます', ['to play', 'amuse']],
        ['ゲームをします', 'to play a game'],
    ]
}

b1u10 = {
    'l1': [
        ['どうですか', 'what happened?'],
        ['びょうき', ['illness', 'sickness']],
        ['かぜ', 'a cold'],
        ['ねつ', 'a fever'],
        ['いたい', ['painful', 'sore']],
        ['だいじょうぶ', 'alright'],
        ['しにます', 'to die'],
        ['かわいそうに', 'hot pitiful'],
    ],
    'l2': [
        ['やすみます', 'to rest'],
        ['（がっこうを）やすみます', 'to be absent (from school)'],
        ['くすりをのみます', 'to take medicine'],
        ['ゆうべ', 'last night'],
        ['けさ', 'this morning'],
        ['こんばん', 'tonight'],
        ['ねむい', 'sleepy'],
        ['つかれています', 'is tired'],
        ['はやく', 'early'],
        ['おすく', 'late'],
    ],
    'l3': [
        ['しあい', '(sports) game'],
        ['わたしたち', 'we'],
        ['ぼくたち', 'we (males)'],
        ['チーム', 'team'],
        ['かちます', 'to win'],
        ['まけます', 'to lose'],
        ['つよい', 'strong'],
        ['よわい', 'weak'],
    ],
    'l4': [
        ['はる', 'spring'],
        ['なつ', 'summer'],
        ['あき', 'fall'],
        ['ふゆ', 'winter'],
        ['せんげつ', 'last month'],
        ['こんげつ', 'this month'],
        ['らいげつ', 'next month'],
        ['まいつき', 'every month'],
        ['だいじ', 'important'],
        ['がんばって', ['good luck', 'do your best']],
        ['がんばります', 'I will do my best'],
    ],
    'l5': [
        ['だいがく', ['college', 'university']],
        ['だいがくせい', 'college student'],
        ['～のまえに', 'before ~'],
        ['～のあとで', 'after ~'],
        ['～であいます', 'to meet at a place'],
        ['れんしゅうをします', 'to practice'],
        ['はしります', 'to run'],
    ],
    'all': [
        ['どうですか', 'what happened?'],
        ['びょうき', ['illness', 'sickness']],
        ['かぜ', 'a cold'],
        ['ねつ', 'a fever'],
        ['いたい', ['painful', 'sore']],
        ['だいじょうぶ', 'alright'],
        ['しにます', 'to die'],
        ['かわいそうに', 'hot pitiful'],
        ['やすみます', 'to rest'],
        ['（がっこうを）やすみます', 'to be absent (from school)'],
        ['くすりをのみます', 'to take medicine'],
        ['ゆうべ', 'last night'],
        ['けさ', 'this morning'],
        ['こんばん', 'tonight'],
        ['ねむい', 'sleepy'],
        ['つかれています', 'is tired'],
        ['はやく', 'early'],
        ['おすく', 'late'],
        ['しあい', '(sports) game'],
        ['わたしたち', 'we'],
        ['ぼくたち', 'we (males)'],
        ['チーム', 'team'],
        ['かちます', 'to win'],
        ['まけます', 'to lose'],
        ['つよい', 'strong'],
        ['よわい', 'weak'],
        ['はる', 'spring'],
        ['なつ', 'summer'],
        ['あき', 'fall'],
        ['ふゆ', 'winter'],
        ['せんげつ', 'last month'],
        ['こんげつ', 'this month'],
        ['らいげつ', 'next month'],
        ['まいつき', 'every month'],
        ['だいじ', 'important'],
        ['がんばって', ['good luck', 'do your best']],
        ['がんばります', 'I will do my best'],
        ['だいがく', ['college', 'university']],
        ['だいがくせい', 'college student'],
        ['～のまえに', 'before ~'],
        ['～のあとで', 'after ~'],
        ['～であいます', 'to meet at a place'],
        ['れんしゅうをします', 'to practice'],
        ['はしります', 'to run'],
    ]
}

b1u11 = {
    'l2': [
        ['すわってください', 'please sit'],
        ['たってください', 'please stand'],
        ['～をだしてください', 'please turn in (something)'],
        ['～をみせてください', 'please show me (something)'],
        ['まどをあけてください', 'please open the window'],
        ['ドアをしめてください', 'please close the door'],
        ['しずかにしてください', 'please be quiet'],
        ['もういちどいってください', 'please say it one more time'],
        ['ちょっとまってください', 'please wait a minute'],
        ['（お）みせ', 'store'],
        ['すみません', 'excuse me'],
    ],
    'l3': [
        ['シャツ', 'shirt'],
        ['ジャケット', 'jacket'],
        [['パンツ', 'ズボン'], 'pants'],
        ['くつ', 'shows'],
        ['とけい', ['watch', 'clock']],
        ['スーパー', 'supermarket'],
        ['ほんや', 'bookstore'],
        ['はなや', 'flower shop'],
        ['すしや', 'sushi shop/bar'],
        ['きっさてん', 'cofee shop'],
        ['かいます', 'to buy'],
    ],
    'l4': [
        ['（お）いくらですか', 'how much?'],
        ['～ぐらい', 'about ~'],
        ['どれですか', 'which one?'],
        ['どの～', 'which ~'],
    ],
    'l5': [
        ['たかい', 'expensive'],
        ['やすい', 'cheap'],
        ['おいしい', 'delicious'],
        ['まずい', 'unappetizing'],
        ['つごい', 'is teriffic/terrible'],
        ['すばらしい', 'is wonderful'],
        ['～はいかがですか', 'how about ~?'],
        ['わあ', 'wow!']
    ],
    'all': [
        ['すわってください', 'please sit'],
        ['たってください', 'please stand'],
        ['～をだしてください', 'please turn in (something)'],
        ['～をみせてください', 'please show me (something)'],
        ['まどをあけてください', 'please open the window'],
        ['ドアをしめてください', 'please close the door'],
        ['しずかにしてください', 'please be quiet'],
        ['もういちどいってください', 'please say it one more time'],
        ['ちょっとまってください', 'please wait a minute'],
        ['（お）みせ', 'store'],
        ['すみません', 'excuse me'],
        ['シャツ', 'shirt'],
        ['ジャケット', 'jacket'],
        [['パンツ', 'ズボン'], 'pants'],
        ['くつ', 'shows'],
        ['とけい', ['watch', 'clock']],
        ['スーパー', 'supermarket'],
        ['ほんや', 'bookstore'],
        ['はなや', 'flower shop'],
        ['すしや', 'sushi shop/bar'],
        ['きっさてん', 'cofee shop'],
        ['かいます', 'to buy'],
        ['（お）いくらですか', 'how much?'],
        ['～ぐらい', 'about ~'],
        ['どれですか', 'which one?'],
        ['どの～', 'which ~'],
        ['たかい', 'expensive'],
        ['やすい', 'cheap'],
        ['おいしい', 'delicious'],
        ['まずい', 'unappetizing'],
        ['つごい', 'is teriffic/terrible'],
        ['すばらしい', 'is wonderful'],
        ['～はいかがですか', 'how about ~?'],
        ['わあ', 'wow!']
    ]
}

b1u12 = {
    'l1': [
        ['おなかがすきました', 'I got hungry'],
        ['おなかがペコペコです', 'I am hungry'],
        ['のどがかわきました', 'I got thirsty'],
        ['のどがカラカラです', 'I am thirsty'],
        ['もう(+aff.)', 'already'],
        ['いいえ、まだです', 'no, not yet'],
        ['じゃ', 'well then (informal)'],
        ['では', 'well then (formal)'],
    ],
    'l2': [
        ['ピサ', 'pizza'],
        ['ハンバーガー', 'hamburger'],
        ['ホットドッグ', 'hot dog'],
        ['サンドイッチ', 'sandwich'],
        ['サラダ', 'salad'],
        ['フライドポテト', 'french fries'],
        ['（お）べんとう', 'boxed lunch'],
        [['（お）むすび', '（お）にぎり'], 'rice ball'],
        ['サイズ', 'size'],
        [['Sサイズ', 'エスサイズ'], 'small size'],
        [['Mサイズ', 'エムサイズ'], 'medium size'],
        [['Lサイズ', 'エルサイズ'], 'large size'],
        ['ぜんぶ', 'everything'],
        ['ぜんぶで', 'for all'],
    ],
    'l3': [
        ['（お）はし', 'chopsticks'],
        ['フォーク', 'fork'],
        ['スプーン', 'spoon'],
        ['ナイフ', 'knife'],
        ['ストロー', 'straw'],
        ['（お）さら', ['(a) plate', '(a) dish']],
        ['コップ', 'cup'],
        ['ナプキン', 'napkin'],
        ['フォークで', 'with a fork'],
        ['いいえ、けこうです', 'no, thank you'],
        ['わすれました', 'I forgot'],
        ['～がいります', 'need ~'],
        ['～がかしてください', 'please lend me ~'],
    ],
    'l4': [
        ['つめたい', 'cold (to the touch)'],
        ['あたたかい', 'warm (to the touch)'],
        ['もういっぱい', 'one more cup'],
        ['いただきます', 'I will recieve'],
        ['ごちそうさま', 'it was a feast'],
        ['おなかがいっぱいです', 'I am full'],
    ],
    'l5': [
        ['じゃ、またあとで', 'well then, see you later (informal)'],
        ['では、またあとで', 'well then, see you later (formal)'],
        ['バイバイ', 'good bye'],
        ['これから', 'from now on'],
        ['それから', 'and then'],
    ],
    'all': [
        ['おなかがすきました', 'I got hungry'],
        ['おなかがペコペコです', 'I am hungry'],
        ['のどがかわきました', 'I got thirsty'],
        ['のどがカラカラです', 'I am thirsty'],
        ['もう(+aff.)', 'already'],
        ['いいえ、まだです', 'no, not yet'],
        ['じゃ', 'well then (informal)'],
        ['では', 'well then (formal)'],
        ['ピサ', 'pizza'],
        ['ハンバーガー', 'hamburger'],
        ['ホットドッグ', 'hot dog'],
        ['サンドイッチ', 'sandwich'],
        ['サラダ', 'salad'],
        ['フライドポテト', 'french fries'],
        ['（お）べんとう', 'boxed lunch'],
        [['（お）むすび', '（お）にぎり'], 'rice ball'],
        ['サイズ', 'size'],
        [['Sサイズ', 'エスサイズ'], 'small size'],
        [['Mサイズ', 'エムサイズ'], 'medium size'],
        [['Lサイズ', 'エルサイズ'], 'large size'],
        ['ぜんぶ', 'everything'],
        ['ぜんぶで', 'for all'],
        ['（お）はし', 'chopsticks'],
        ['フォーク', 'fork'],
        ['スプーン', 'spoon'],
        ['ナイフ', 'knife'],
        ['ストロー', 'straw'],
        ['（お）さら', ['(a) plate', '(a) dish']],
        ['コップ', 'cup'],
        ['ナプキン', 'napkin'],
        ['フォークで', 'with a fork'],
        ['いいえ、けこうです', 'no, thank you'],
        ['わすれました', 'I forgot'],
        ['～がいります', 'need ~'],
        ['～がかしてください', 'please lend me ~'],
        ['つめたい', 'cold (to the touch)'],
        ['あたたかい', 'warm (to the touch)'],
        ['もういっぱい', 'one more cup'],
        ['いただきます', 'I will recieve'],
        ['ごちそうさま', 'it was a feast'],
        ['おなかがいっぱいです', 'I am full'],
        ['じゃ、またあとで', 'well then, see you later (informal)'],
        ['では、またあとで', 'well then, see you later (formal)'],
        ['バイバイ', 'good bye'],
        ['これから', 'from now on'],
        ['それから', 'and then'],
    ]
}

b2u1 = {
    'l1': [
        ['でんわばんごう', '(tele)phone number'],
        ['じゅうしょ', 'address'],
        ['～でうまれました', 'was born in'],
        ['～にすんでいます', ['(to) live in', '(to) reside in']],
        ['～につとめています', 'is employed (at)'],
        ['～ではたらいています', 'is working (at)'],
        ['アルバイトをしています', 'is working part time'],
        ['～と けっこんしています', 'is married (to)'],
        ['もっています', ['(to) have', '(to) possess', '(to) hold', '(to) carry']],
        ['ならっています', 'is learning'],
        ['ホームステイをします', 'will do a homestay'],
    ],
    'l2': [
        ['うえ', ['above', 'on', 'on top of']],
        ['した', ['below', 'under']],
        ['なか', 'inside'],
        ['そと', 'outside'],
        ['まえ', 'in front (of)'],
        ['うしろ', ['behind', 'back']],
        ['みぎ', 'right (side)'],
        ['ひだり', 'left (side)'],
        ['そば', ['nearby', 'by']],
        ['あいだ', 'between'],
        ['となり', 'next to'],
        ['ちかく', ['nearby', 'vicinity']],
    ],
    'l3': [
        ['いえ', 'house'],
        ['ぎんこう', 'bank'],
        ['こうえん', 'park'],
        ['りょう', 'dormitory'],
        ['あかちゃん', 'baby'],
        ['~ちゃん', ['young', 'small', 'cute']],
        ['まだ(+aff.)', 'still'],
        ['まだ(+neg.)', 'not yet'],
        ['もう(+aff.)', 'already'],
        ['もう(+neg.)', 'not anymore'],
        ['~について', 'about (topic)'],
        ['しょうかい(を)します', 'to introduce'],
        ['じこしょうかい(を)します', 'to do a self introduction'],
    ],
    'l4': [
        ['とくに', 'especially'],
        ['ごりょしん', '(someone else\'s) parents'],
        ['りょしん', '(one\'s) own parents'],
        ['ただしい', 'is correct'],
        ['ちがいます', ['is wrong', 'to differ']],
        ['しつもん', 'question'],
        ['しつもんをします', 'to ask a question'],
        ['こたえ', 'answer'],
        ['こたえます', 'to answer'],
    ],
    'all': [
        ['でんわばんごう', '(tele)phone number'],
        ['じゅうしょ', 'address'],
        ['～でうまれました', 'was born in'],
        ['～にすんでいます', ['(to) live in', '(to) reside in']],
        ['～につとめています', 'is employed (at)'],
        ['～ではたらいています', 'is working (at)'],
        ['アルバイトをしています', 'is working part time'],
        ['～と けっこんしています', 'is married (to)'],
        ['もっています', ['(to) have', '(to) possess', '(to) hold', '(to) carry']],
        ['ならっています', 'is learning'],
        ['ホームステイをします', 'will do a homestay'],
        ['うえ', ['above', 'on', 'on top of']],
        ['した', ['below', 'under']],
        ['なか', 'inside'],
        ['そと', 'outside'],
        ['まえ', 'in front (of)'],
        ['うしろ', ['behind', 'back']],
        ['みぎ', 'right (side)'],
        ['ひだり', 'left (side)'],
        ['そば', ['nearby', 'by']],
        ['あいだ', 'between'],
        ['となり', 'next to'],
        ['ちかく', ['nearby', 'vicinity']],
        ['いえ', 'house'],
        ['ぎんこう', 'bank'],
        ['こうえん', 'park'],
        ['りょう', 'dormitory'],
        ['あかちゃん', 'baby'],
        ['~ちゃん', ['young', 'small', 'cute']],
        ['まだ(+aff.)', 'still'],
        ['まだ(+neg.)', 'not yet'],
        ['もう(+aff.)', 'already'],
        ['もう(+neg.)', 'not anymore'],
        ['~について', 'about (topic)'],
        ['しょうかい(を)します', 'to introduce'],
        ['じこしょうかい(を)します', 'to do a self introduction'],
        ['とくに', 'especially'],
        ['ごりょしん', '(someone else\'s) parents'],
        ['りょしん', '(one\'s) own parents'],
        ['ただしい', 'is correct'],
        ['ちがいます', ['is wrong', 'to differ']],
        ['しつもん', 'question'],
        ['しつもんをします', 'to ask a question'],
        ['こたえ', 'answer'],
        ['こたえます', 'to answer'],
    ]
}

b2u2 = {
    'l1': [
        ['きています', 'is wearing above waist'],
        ['はいています', 'is wearing below waist'],
        ['しています', 'is wearing accessories'],
        ['かぶっています', 'is wearing on head'],
        ['かけています', 'is wearing (glasses)'],
        ['ふく', 'clothing'],
        [['Ｔシャツ', 'ティーシャツ', 'テイーシャツ'], 'T-shirt'],
        ['ズボン', 'pants'],
        [['ショートパンツ', 'ショーツ'], 'shorts'],
        ['セーター', 'sweater'],
        ['ワンピース', 'dress'],
        ['スカート', 'skirt'],
        ['せいふく', 'uniform'],
        [['くつ下', 'ソックス'], 'socks'],
        ['ゆびわ', 'ring'],
        ['めがね', 'glasses'],
        ['サングラス', 'sunglasses'],
        ['ネックレス', 'necklace'],
        ['イヤリング', 'earrings'],
        ['ピアス', 'pierced (earrings)'],
    ],
    'l2': [
        ['きそく', ['rules', 'regulations']],
        ['じゆう', ['free', 'liberal']],
        ['いけません', ['won\'t do', 'must not do']],
        ['かまいません', '(I) do not mind if...'],
        ['ガムをかみます', 'to chew gum'],
        ['ごみをすてます', ['to litter', 'to throw away trash']],
        ['うんてんをします', 'to drive'],
        ['～にあいます', 'to meet (someone)'],
        ['～にききます', 'to ask (someone)'],
        ['ぜったい（に）', 'absolutely (negative)'],
    ],
    'l3': [
        ['かります', 'to borrow'],
        ['きをつけて', 'to be careful'],
        ['えいがかん', 'movie theater'],
        ['しょうめいしょ', 'I.D.'],
        ['うんてんめんきょ', 'driver\'s license'],
        ['パスポート', 'passport'],
        ['ところで', 'by the way'],
    ],
    'l4': [
        ['～が見えます', '~ can be seen'],
        ['～がきこえます', ['~ can be heard', 'audible']],
        ['もん', 'gate'],
        ['ほんとうに', ['really', 'truly']],
        ['ほんとうですか', ['is that true?', 'is that real?']],
        ['～だけ', 'only ~'],

    ],
    'all': [
        ['きています', 'is wearing above waist'],
        ['はいています', 'is wearing below waist'],
        ['しています', 'is wearing accessories'],
        ['かぶっています', 'is wearing on head'],
        ['かけています', 'is wearing (glasses)'],
        ['ふく', 'clothing'],
        [['Ｔシャツ', 'ティーシャツ', 'テイーシャツ'], 'T-shirt'],
        ['ズボン', 'pants'],
        [['ショートパンツ', 'ショーツ'], 'shorts'],
        ['セーター', 'sweater'],
        ['ワンピース', 'dress'],
        ['スカート', 'skirt'],
        ['せいふく', 'uniform'],
        [['くつ下', 'ソックス'], 'socks'],
        ['ゆびわ', 'ring'],
        ['めがね', 'glasses'],
        ['サングラス', 'sunglasses'],
        ['ネックレス', 'necklace'],
        ['イヤリング', 'earrings'],
        ['ピアス', 'pierced (earrings)'],
        ['きそく', ['rules', 'regulations']],
        ['じゆう', ['free', 'liberal']],
        ['いけません', ['won\'t (do)', 'must not (do)']],
        ['かまいません', '(I) do not mind if...'],
        ['ガムをかみます', 'to chew gum'],
        ['ごみをすてます', ['to litter', 'to throw away trash']],
        ['うんてんをします', 'to drive'],
        ['～にあいます', 'to meet (someone)'],
        ['～にききます', 'to ask (someone)'],
        ['ぜったい（に）', 'absolutely (negative)'],
        ['かります', 'to borrow'],
        ['きをつけて', 'to be careful'],
        ['えいがかん', 'movie theater'],
        ['しょうめいしょ', 'I.D.'],
        ['うんてんめんきょ', 'driver\'s license'],
        ['パスポート', 'passport'],
        ['ところで', 'by the way'],
        ['～が見えます', '~ can be seen'],
        ['～がきこえます', ['~ can be heard', 'audible']],
        ['もん', 'gate'],
        ['ほんとうに', ['really', 'truly']],
        ['ほんとうですか', ['is that true?', 'is that real?']],
        ['～だけ', 'only ~'],
    ]
}

b2u3 = {
    'l1': [
        ['こうつうじこ', 'traffic accident'],
        ['しんごう', 'traffic lights'],
        ['あか、き色、あお', 'red, yellow, green'],
        ['パトカー', 'police car'],
        ['きゅうきゅう車', 'ambulance'],
        ['みち', ['street', 'road']],
        ['かど', 'corner'],
        [['うんてん手', 'ドライバー'], 'driver'],
        ['かぎ', 'key'],
    ],
    'l2': [
        ['うん', 'yes (informal)'],
        ['ううん', 'no (informal)'],
        ['けっして(+neg.)', 'never'],
        ['しんぱい（を）する', 'to worry'],
        ['けんか（を）する', 'to have a fight'],
        ['～にはいる', 'to enter (a place)'],
        ['～を出る', ['to exit', 'get out of (a place)']],
        ['つかう', 'to use'],
    ],
    'l3': [
        ['あぶない', 'dangerous'],
        ['あんぜん', 'safe'],
        ['こわい', 'scary'],
        ['早く', ['early', 'quickly']],
        ['きゅうに', 'suddenly'],
        ['を(not particle)', ['along', 'through']],
        [['～にとまる', '～でとまる'], 'to stop'],
        [['～でまがる', '～をまがる'], ['to turn at', 'along (a place)']],
        ['スピードを出す', 'to speed'],
    ],
    'l4': [
        ['～にのる', 'to ride (vehicle)'],
        [['～をおりる', '～からおりる'], 'to get off/out (vehicle)'],
        ['シートベルトをする', 'to wear aseat belt'],
        ['出かける', 'to go out'],
        [['～をでる', '～からでる'], 'to leave (a place)'],
        ['～につく', 'to arrive (at a place)'],
        ['おしえる', 'to teach'],
    ],
    'all': [
        ['こうつうじこ', 'traffic accident'],
        ['しんごう', 'traffic lights'],
        ['あか、き色、あお', 'red, yellow, green'],
        ['パトカー', 'police car'],
        ['きゅうきゅう車', 'ambulance'],
        ['みち', ['street', 'road']],
        ['かど', 'corner'],
        [['うんてん手', 'ドライバー'], 'driver'],
        ['かぎ', 'key'],
        ['うん', 'yes (informal)'],
        ['ううん', 'no (informal)'],
        ['けっして(+neg.)', 'never'],
        ['しんぱい（を）する', 'to worry'],
        ['けんか（を）する', 'to have a fight'],
        ['～にはいる', 'to enter (a place)'],
        ['～を出る', ['to exit', 'get out of (a place)']],
        ['つかう', 'to use'],
        ['あぶない', 'dangerous'],
        ['あんぜん', 'safe'],
        ['こわい', 'scary'],
        ['早く', ['early', 'quickly']],
        ['きゅうに', 'suddenly'],
        ['を(not particle)', ['along', 'through']],
        [['～にとまる', '～でとまる'], 'to stop'],
        [['～でまがる', '～をまがる'], ['to turn at', 'along (a place)']],
        ['スピードを出す', 'to speed'],
        ['～にのる', 'to ride (vehicle)'],
        [['～をおりる', '～からおりる'], ['to get off', 'to get out (vehicle)']],
        ['シートベルトをする', 'to wear a seatbelt'],
        ['出かける', 'to go out'],
        [['～をでる', '～からでる'], 'to leave (a place)'],
        ['～につく', 'to arrive (at a place)'],
        ['おしえる', 'to teach'],
    ],
    'kanji': [
        ['名', ['な', 'メイ', 'めい']],
        ['外', ['そと', 'ガイ', 'がい']],
        ['前', ['まえ', 'ゼン', 'ぜん']],
        ['話', ['はな（す）', 'ワ', 'わ']],
        ['書', ['かく', 'ショ', 'しょ']],
        ['何', ['なに', 'なん']],
        ['見（む）', ''],
        ['食（べる）', ],
        ['言（う）', ''],
        ['手', 'しゅ'],
        ['夕方', ''],
        ['漢字', 'かんじ'],
    ]
}

resources = {
    '1.1.0': b1u1['all'],
    '1.1.1': b1u1['l1'],
    '1.1.2': b1u1['l2'],
    '1.1.3': b1u1['l3'],
    '1.1.4': b1u1['l4'],
    '1.1.5': b1u1['l5'],
    '1.1.6': b1u1['l6'],

    '1.9.0': b1u9['all'],
    '1.9.1': b1u9['l1'],
    '1.9.2': b1u9['l2'],
    '1.9.3': b1u9['l3'],
    '1.9.4': b1u9['l4'],
    '1.9.5': b1u9['l5'],

    '1.10.0': b1u10['all'],
    '1.10.1': b1u10['l1'],
    '1.10.2': b1u10['l2'],
    '1.10.3': b1u10['l3'],
    '1.10.4': b1u10['l4'],
    '1.10.5': b1u10['l5'],
    
    '1.11.0': b1u11['all'],
    # There is no lesson 1
    '1.11.2': b1u11['l2'],
    '1.11.3': b1u11['l3'],
    '1.11.4': b1u11['l4'],
    '1.11.5': b1u11['l5'],

    '1.12.0': b1u12['all'],
    '1.12.1': b1u12['l1'],
    '1.12.2': b1u12['l2'],
    '1.12.3': b1u12['l3'],
    '1.12.4': b1u12['l4'],
    '1.12.5': b1u12['l5'],

    '2.2.0': b2u2['all'],
    '2.2.1': b2u2['l1'],
    '2.2.2': b2u2['l2'],
    '2.2.3': b2u2['l3'],
    '2.2.4': b2u2['l4'],

    '2.3.0': b2u3['all'],
    '2.3.1': b2u3['l1'],
    '2.3.1': b2u3['l2'],
    '2.3.1': b2u3['l3'],
    '2.3.1': b2u3['l4'],
    '2-3': b2u3['kanji']
}

